### ISSUE TITLE
QUESTION: Is there a convenient API for upgrading to a higher Leap version?

### ISSUE THREAD

**Issue by JonathanKang** [openSUSE/libzypp#209]
I'm integrating GNOME Software's distribution upgrade feature into Leap. I need implement PackageKit's zypp backend to upgrade Leap. Do I need manually replace the version number in repo url and "dup" the system? Is there any other convenient way for this?

Thanks

**Comment by mlandres** [comment]
Short: No

Right, you need to disable/remove the old repos, enable/add the new repos and the ''dup.

The transition from old repos to new repos solely depends on how the repositories are set up by the user, or yast, or.... There is no common rule. Trouble starts with the `baseurl` entry of a repository (apart from the fact that there could be multiple baseurls defined for one repo and some people prefer to manually enter a mirror URL):

There may be a verbatim version:
> baseurl=https://download.opensuse.org/distribution/leap/15.1/repo/oss

Or using the builtin `${RELEASEVER}` mechanism (application may ask libzypp to fake the RELEASEVER, otherwise it's derived from the installed product).
> baseurl=https://download.opensuse.org/distribution/leap/${RELEASEVER}/repo/oss

Or, if you prefer to control it on your own, uses a custom variable (defined in `/etc/zypp/vars.d`):
> baseurl=https://download.opensuse.org/distribution/leap/${SOME_VARNAME}/repo/oss

And finally on top of this, some people may use a `service` as a convenient way to ship and maintain the bunch of  openSUSE repos (outlined [here](https://doc.opensuse.org/projects/libzypp/HEAD/zypp-services.html#services-usecase-4)). To amend the service repos URLs, you need to amend or switch the service.

If openSUSE would maintain and offer such services per distro, you could quite easily switch at least the core set of repositories by switching the service. Then you'd just need to care about the users custom repos (packman,obs,etc.).

Anyhow, if you mess up the repos, you mess up the dup result. As there's no common way to prepare the repos noninteractively, there's no API for this in libzypp. The user is responsible for having adjusted the repos before calling dup.
