### ISSUE TITLE
Make libzypp/zypper tranfer packages parallelly.

### ISSUE THREAD

**Issue by 210hcl** [openSUSE/libzypp#238]
On July 22, 2019, the auther of curl, Daniel make curl goes parallel. [This](https://daniel.haxx.se/blog/2019/07/22/curl-goez-parallel/) is the link. Is it possile to use this feature to make libzypp/zypper to tranfer rpm packages parallelly?

**Comment by mlandres** [comment]
Since 2010 zypps MultiCurl backend supports MetaLink. Packages downloaded  from download.opensuse.org (or from any other server supporting MetaLink), already use multiple connections to different mirror severs in parallel to download a single rpm.
But you're right, we still have some gaps between the packages and we're about to fix this. It's currently WIP in the DEV_NZYPP  branch and will be published as soon as it's done.

**Comment by oshanz** [comment]
https://github.com/openSUSE/zypper/issues/104
