### ISSUE TITLE
[QUESTION] Any way to do distribution upgrade?

### ISSUE THREAD

**Issue by JonathanKang** [openSUSE/libzypp#328]
Hi libzypp maintainers,

I'm currently implementing GNOME Software's distro upgrade support for openSUSE/SLE. The main problem I met is the whole upgrade process needs to be implemented in PackageKit's zypp backend using libzypp, and I'm not quite sure this is implementable using libzypp.

I've done a bit research online and found out that you can upgrade the whole system by setting `ZYPP_REPO_RELEASEVER=$a-newer-version` and perform `zypper ref; zypper dup`. Or `zypper --releasever=$a-newer-version ref; zypper --releasever=$a-newer-version dup`. But there might be some problems with the currently existing repos in the old system. Users have to disable some of them before doing this, for example the DVD installation repo. This however, makes the whole process not so automatic.

So I'm wondering whether it is possible to make this whole experience better and make it doable using libzypp APIs.

Thanks
Jonathan Kang

**Comment by mlandres** [comment]
This should be possible because zypper/YAST/PK all use libzypp.

AFAIK PK already has an upgrade system workflow implemented (mostly because TW uses `dup` for updating).

Regarding the repos which need to be adjusted before the dup is performed, this is in the users domain. 
The set of repos active during a dup define the target of the upgrade.

How the repos are adjusted depends on the user and system. 
SLE often uses services provided by SCC to supply the repos. The set is changed after having registered to the new SP. All this registration stuff is handled in the zypper-migration-plugin (maintained outside zypp). 
Regarding `releasever`: Zypp supports using repo variables (see man zypper; defined in `/etc/zypp/vars.d`) in a repos URL and name. `$[releasever}` is one of the few variables zypp provides built in (unless you define it in etc/zypp/vars.d/releasever), and which can even be overwritten on the commandline. But whether repos actualy use $[releasever} in their URL depends on the user or on the tools that created the repo. Also whether the remaining repos had to be disabled or replaced by repos suitable for the new distro, is nothing zypp can judge. The user has to confirm this.

openSUSE could ease the task by providing a RIS service that defines all the core repos of a distro. But AFAIK they don't and so most systems still use a bunch of individual source/debug/update/oss/non-oss... repos, rather than one service URL, that defines all those repos for a distro.

**Comment by JonathanKang** [comment]
> Regarding the repos which need to be adjusted before the dup is performed, this is in the users domain.

So the main focus should be getting the set of repos right before upgrading. 

> But whether repos actualy use $[releasever} in their URL depends on the user or on the tools that created the repo.

The default repo created by fresh installations works well. You can use --releasever=$a-newer-version to replace the old version string. It can be a problem for other repos. Just to confirm, setting `ZYPP_REPO_RELEASEVER` in the code should work as well, right?

**Comment by mlandres** [comment]
Getting the set of repos right before upgrading is the crucial point. It makes a big difference whether you simply disable a 3rd party repo (nvidia/packman/obs) or if you replace it by a repo that fits the new target distro. If you disable a repo, the packages installed from there will be replaced by packages from the the now enabled repos or, if not available, may get deleted. If you provide updated repos for them, their packages will updated as expected. This is especially important for 3rd party repos which provide drivers (nvidia) or software SUSE does not provide. Usually their packages must not be deleted, so you want to wait for new repos being available for them.

Whether setting the environment variable works for you depends on how PK works. If you set this variable for the backend, then commands executed by the backend and those outside (zypper/YAST) will see different repo urls. Each will refresh the repos to the version they are seeing. So it is important that the PK code refreshing the repos and the code doing the upgrade share the same zypplock (i.e. no operation from outside PK can interfere and refresh back to the 'old' releasever).

The system wide default for ${releasever} is autodetected unless `/etc/zypp/vars.d/releasever` exists (the 1st line in the file defines the value). The value is read once at the time the Target is initialized. The environment variable is able to overwrite this value at any time.

**Comment by JonathanKang** [comment]
Thank you so much for these information. They are very useful!
