### ISSUE TITLE
zypp::Url("dir:///foo").asCompleteString() returns "dir:/foo", having undefined authority instead of empty

### ISSUE THREAD

**Issue by mvidner** [openSUSE/libzypp#441]
Hi!

I found this when YaST builds started failing with Ruby 3.2. 

> `URI("dir:///foo").to_s` no longer returns `"dir:/foo"` https://bugzilla.suse.com/show_bug.cgi?id=1207239
> (It's not not causally related to this, but some code *compares* URIs handled by Ruby and Zypp and there it fails)

IIUC, the difference is in the *authority* component, where three slashes mean it is *empty* and a single slash means it is *undefined* (https://en.wikipedia.org/wiki/Uniform_Resource_Identifier)

Test code:

```cpp
#include <zypp/Url.h>
#include <string>
#include <iostream>
using namespace std;

int main() {
  string before { "dir:///" };
  zypp::Url u { before };
  string after { u.asCompleteString() };

  
  cout << before << endl;
  cout << u << endl;
  cout << after << endl;
  return 0;
}
```

Running this on Tumbleweed:
```console
$ c++ -o urltest -lzypp urltest.cc
$ ./urltest
dir:///
dir:/
dir:/
```

**Comment by mvidner** [comment]
For my reference, the failing package is `yast2-packager`, using a C++ binding in `yast2-pkg-bindings`. Reproducer:

```console
$ ruby -r yast -e 's = "dir:///foo"; Yast.import "Pkg"; p Yast::Pkg.ExpandedUrl(s)'
"dir:/foo"
```

**Comment by mlandres** [comment]
This is a legacy  we probably will not fix/change.

Schemata like _hd_,_cd_,_dvd_,_dir_,_iso_ actually do not allow an authority. You immediately recognize this, if you try to define one:
```
---[dir:/]
dir:/
---[dir:///]
dir:/
---[dir://user@/]
UrlBase.cc(setUsername):1027: Url scheme does not allow a username
---[dir://:pass@/]
UrlBase.cc(setPassword):1061: Url scheme does not allow a password
---[dir://host/]
UrlBase.cc(setHost):1100: Url scheme does not allow a host component
---[dir://:port/]
UrlBase.cc(setPort):1148: Url scheme does not allow a port
```

The _file_ schema allows an optional host part:
```
---[file:/]
file:/
---[file:///]
file:/
---[file://user@/]
UrlBase.cc(checkUrlData):221: Url scheme does not allow a username
---[file://:pass@/]
UrlBase.cc(checkUrlData):221: Url scheme does not allow a password
---[file://host/]
file://host/
---[file://:port/]
UrlBase.cc(setPort):1148: Url scheme does not allow a port
```

The implementation (from 2005) however always allows an empty authority (a `//` followed by nothing; i.e. an empty hostname). This could be considered as a bug and the correct behavior would be to _throw_ on `dir:///` because no authority is allowed by the schema and on 'file:///` because the host component is missing/empty. OTOH there is no semantical difference between both forms in zypp. Both define a Url with an empty authority which is the same as no authority.

At the time this was recognized `dir:///`  and  'file:///` formats were already in use and even used in documentation. That's why we never considered to change this and to break a lot of things by throwing an exception if the triple-slash is used.

In libzypp-17.11.1 (2019) we  changed the asString methods not to print an empty authority if the schema actually does not require it (or wven forbids it). And a schema requiring an authority will throw if the host part is empty.

So the triple-slash is a legacy format we accept as input but we do not use it in output.
